### ISSUE TITLE
Cannot access the guide through browsers

### ISSUE THREAD

**Issue by quangIO** [fschutt/azul.rs#1]
Some files don't have .html extension, so Github page responds with `content-type: application/octet-stream` (e.g. `curl https://azul.rs/guide/nightly/Installation -i | less`). I think a quick fix would be removing all non-html files in /guide/nightly

edit: the html files looks like markdown ones. Anyway, I found those documentation at https://github.com/fschutt/azul/blob/master/api/_patches/html/guide/ nice enough already.

**Comment by fschutt** [comment]
Yes, the documentation is outdated, I basically just copied the old wiki to the website because I want to transition away from GitHub as much as possible in the future.

The files should have an .html extension, they are generated from the markdown files.

Sorry for the late reply, I accidentally turned off notifications on GitHub.

**Comment by fschutt** [comment]
Fixed: 

![image](https://user-images.githubusercontent.com/12084016/116768758-60debd00-aa39-11eb-808c-ec17d70eb0d2.png)

However, the guide hasn't yet been updated properly and is very outdated.
